name: "CI/CD for Chicken Streamlit App"

on:
  push: 
    branches: [main]

jobs: 
  ci: 
    runs-on: ubuntu-latest 
    strategy:
      matrix: 
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4.2.0

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies 
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt 

      - name: Analyze the code with Pylint 
        run: 
          pylint $(git ls-files "*.py") 

  cd: 
    runs-on: ubuntu-latest 
    needs: [ci]
    if: ${{ !contains(steps.get_commit_message.outputs.message, "No Deploy") }}
    
    steps: 
      - uses: actions/checkout@v4.2.0

      - name: Deployment
        uses: easingthemes/ssh-deploy@main
        env: 
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SCRIPT_AFTER: | 
            echo "Updating the package list" 
            sudo apt update 
            echo "Installing pip" 
            sudo apt install -y python3-pip python3-venv
            echo "Enable the Virtual Env" 
            python3 -m venv venv 
            echo "Activate the venv" 
            source venv/bin/activate
            echo "Installing the requirements" 
            python3 -m pip install -r requirements.txt 
            echo "Running Streamlit" 
            sudo nohup venv/bin/streamlit run app.py --server.port 80 > streamlit.log 2>&1 & 
