name: "CI/CD for Chicken Streamlit App"

on:
  push: 
    branches: [main]

jobs: 
  ci: 
    runs-on: ubuntu-latest 
    strategy:
      matrix: 
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4.2.0

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies 
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt 

      - name: Analyze the code with Pylint 
        run: 
          pylint $(git ls-files "*.py") 

  cd: 
    runs-on: ubuntu-latest 
    needs: [ci]

    steps: 
      - uses: actions/checkout@v4.2.0

      - name: Deployment
        uses: easingthemes/ssh-deploy@main
        env: 
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
